### ISSUE TITLE
Is the data set <Cityscapes-VIS> complete？

### ISSUE THREAD

**Issue by daydreamer2023** [SeokjuLee/Insta-DM#6]
Hi, Seokju!
I get only 1636 iterms, but the "train.txt" and "val.txt" indicate there should be 4883+602 = 5485.
Did I make a mistake?
![image](https://user-images.githubusercontent.com/19202609/136429711-ef40db29-e1e5-435b-9bb5-60fe1c9f0d0a.png)
![image](https://user-images.githubusercontent.com/19202609/136429892-6f679c00-c3de-4325-81ac-25800949bb00.png)

**Comment by SeokjuLee** [comment]
Hi, I checked the image zip file, and it contains 5485 scenes. Could you please download the file again?
Thanks!
![image](https://user-images.githubusercontent.com/17178662/136961089-0a77c3a2-26de-478d-9ad1-73df07928f9f.png)

**Comment by daydreamer2023** [comment]
Sorry for the late reply.
I re-downloaded the data set and it is complete.
Thank you for your prompt reply！
