### ISSUE TITLE
ImageNet pretrain

### ISSUE THREAD

**Issue by fengziyue** [SeokjuLee/Insta-DM#9]
Hi, thank you for sharing this amazing work, I just have a little bit confusion. Does the AbsRel error of 0.112 on kitti eigen split with or without imagenet pretraining? If not, do you have results with pretraining?

Thank you

**Comment by SeokjuLee** [comment]
Hi, thank you for your interest! The numbers are the results of our imagenet pretrained model as described in the table in [this section](https://github.com/SeokjuLee/Insta-DM#evaluation). I guess you might be confused by the numbers of MonoDepth2's results in Table 4 in our paper. Sorry for the confusion.

**Comment by fengziyue** [comment]
Thank you for clarifying this! 

I have one more question, in your code, you are always using the models.DispResNet() as depth net. Is this corresponding to the fourth row (DispResNet, AbsRel 0.124) of Table 4 in your paper instead of the eleventh row (ResNet18, AbsRel 0.112)?
If yes, how can I switch to the ResNet18 configuration?

Thank you!

**Comment by SeokjuLee** [comment]
The default configuration of this code is based on the ResNet18 architecture (AbsRel 0.112). In [this line](https://github.com/SeokjuLee/Insta-DM/blob/95fac7f3826045ccf36af12bb4b96b3868bd48ef/train.py#L189), you can see the input configuration of the ResNet types, which is declared in [this line](https://github.com/SeokjuLee/Insta-DM/blob/95fac7f3826045ccf36af12bb4b96b3868bd48ef/train.py#L69). The naming of "DispResNet" is originated from [SC-SfMLearner](https://github.com/JiawangBian/SC-SfMLearner-Release) and [CC](https://github.com/anuragranj/cc).

**Comment by fengziyue** [comment]
Ok, got it. Appreciate your prompt response.
